language: node_js
node_js:
  - 8
install:
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iota-pico/core.git iota-pico/core
  - cd iota-pico/core
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iota-pico/data.git iota-pico/data
  - cd iota-pico/data
  - npm link @iota-pico/core
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iota-pico/crypto.git iota-pico/crypto
  - cd iota-pico/crypto
  - npm link @iota-pico/core @iota-pico/data
  - npm link
  - cd ../pow-nodejs
  - npm link @iota-pico/core @iota-pico/data @iota-pico/crypto
  - npm install
script:
  - npm run dist || travis_terminate 1
  - npm run security || travis_terminate 1
  - npm run test-publish || travis_terminate 1
cache:
  directories:
    - "node_modules"
