language: node_js
node_js:
  - 8
install:
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iotaeco/iota-pico-core.git iotaeco/iota-pico-core
  - cd iotaeco/iota-pico-core
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iotaeco/iota-pico-data.git iotaeco/iota-pico-data
  - cd iotaeco/iota-pico-data
  - npm link @iota-pico/core
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iotaeco/iota-pico-crypto.git iotaeco/iota-pico-crypto
  - cd iotaeco/iota-pico-crypto
  - npm link @iota-pico/core @iota-pico/data
  - npm link
  - cd ../iota-pico-pow-nodejs
  - npm link @iota-pico/core @iota-pico/data @iota-pico/crypto
  - npm install
script:
  - npm run dist
cache:
  directories:
    - "node_modules"
